### ISSUE TITLE
When mountpoint does not have some tags, script fails.

### ISSUE THREAD

**Issue by laama1** [mattyribbo/icecast2-munin#2]
I got certain Icecast config, where my "stream" is main mountpoint and fallback for it is "stream2". But when Live is not playing in "stream" anymore, the mountpoint stays in icecast infopage (example.com:8000) and the script stops working. 
In this case the mountpoint looks like this in the "example.com:8000/admin/stats" page:
```
<source mount="/stream">
<listeners>0</listeners>
<listenurl>http://example.com:8000/stream</listenurl>
<max_listeners>unlimited</max_listeners>
</source>
```
My Icecast version is 2.4.0.
Add next lines inside for-loop to circumvent problem (line 61):

```
        if len(source.childNodes) <= 3:
            continue
```

**Comment by mattyribbo** [comment]
Thanks for reporting this. I'll replicate the problem, check there's no other issues with this fix and commit it as soon as possible.

**Comment by laama1** [comment]
When this situation happens, admin-page stats.xsl looks like this: (look for the mountpoint named "/stream")
http://paste.fedoraproject.org/536453/62931148/

**Comment by mattyribbo** [comment]
Apologies I thought I committed the change. All looked fine when I tested it, will make the change.
